### PR TITLE
bitcoinaddress.js Manage FuckAdBlock as git submodules.

### PR DESCRIPTION
**Pull request by ghost**
Manage submodules through the `git submodule` command. One benefit is that it helps you keep track of the branches and tag IDs of the submodules when you commit, so that checking out ablock-to-bitcoin ensures that the submodules will also contain their right tags.

### CODE REVIEW

**Comment by owocki** [comment]
@erturne thank you for the contribution!

**Comment by ghost** [comment]
I know it's a minor change, but thanks. I saw you mentioned on The Daily Decrypt and thought the idea was interesting.

**Comment by owocki** [comment]
Thanks, the next step is to build relationships enough to get this live in front of end-users; end-game is to prove that bitcoin micro-payments can have similar unit economics to PPC, and therefore are a viable thing.  I'm still getting organized from a lot of feedback today, but will keep you in the loop in case you're interested.

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.05 ETH (34.61 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/owocki/adblock-to-bitcoin/1/517).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Pull request merged**
